" Common Vim Settings
set nocompatible "to get all the vim-only options
set encoding=utf-8 "default encoding to utf-8
set fileencoding=utf-8  " The encoding written to file.
filetype plugin indent on "enable filetype detection
syntax enable "enable syntax highlighting
syntax on

"better indentation for visual mode
vnoremap < <gv
vnoremap > >gv

" some basic settings
set number
set nowrap
"set colorcolumn=80 "add column default
highlight ColorColun ctermbg=233 "make color column red

" linebreak on 79 char
"set lbr
set tw=79

"show whitespace
"MUST be inserted before colorscheme
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
au InsertLeave * match ExtraWhitespace /\s\+$/

"set colorscheme
colorscheme default
set mouse=a

set incsearch " smart searching
set ignorecase " ignore case when searching
set smartcase "unless there's a capital letter there
set hlsearch " highlight search results
set incsearch "higlight search matches as i type
set scrolloff=3 " set three lines around cursor at all times
set wildmenu "better comand line completion
set wildmode=longest,list " wildmode for tab behavior
"set backupdir =~/.vim/backup

" make backspace work like it should
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set lazyredraw " performance config
set magic " for regular expressions

" show matching brackets
set showmatch
set mat=2

" set indents
set tabstop=2
set shiftwidth=2
set autoindent				"Auto indent
set smartindent				"Smart indent
"set smarttab
"set cindent
set expandtab

set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" retrun to last edit position when opening files
autocmd BufReadPost *
  \if line("'\'") > 0 && line("'\'") <= line("$") |
  \  exe "normal! g`\"" |
  \endif
" remember info about open buffers on close
set viminfo^=%

""""""""""""""""""""""""""""""
" => Status line
""""""""""""""""""""""""""""""
" Always show the status line
set laststatus=2

" Format the status line
set statusline=\ %F%m%r%h\

" Pressing ,ss will toggle and untoggle spell checking
map <leader>ss :setlocal spell!<cr>

"----------------------
"Enable Pathogen plugins
"----------------------
execute pathogen#infect()

"----------------------
"NERDTree settings
"----------------------
" set width
let g:NERDTreeWinSize =30

"----------------------
"NERDTree Tabs
"----------------------
" toggle with Ctrl+t
"map <silent> <C-t> :call ToggleVExplorer()<CR>
map <C-t> <plug>NERDTreeTabsToggle<CR>

" Change directory to the current buffer when opening files.
"set autochdir

"------------------
"set per dir vimrc
set exrc
set secure
"-----------------

"----------------------
"vim-prettier
"----------------------
let g:prettier#quickfix_enabled = 0 "disable quickfix
let g:prettier#config#html_whitespace_sensitivity = 'css'

